.TH "GlyphTable" 3 "Sat Oct 9 2010" "Version 1.0" "MessengerSystem" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GlyphTable \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public メソッド"

.in +1c
.ti -1c
.RI "(void) + \fBdrawString:string:withFont:withFontSize:withColor:atX:atY:\fP"
.br
.in -1c
.SH "関数"
.PP 
.SS "+ (void) drawString: (CGContextRef) context(NSString *) str(NSString *) fontName(int) size(UIColor *) color(float) x(float) y"文字列描画プログラム 日本語対応 外部から実行 

.SH "作者"
.PP 
MessengerSystemのソースから Doxygen により生成しました。
